server:
  port: 8080
# 多数据源路由配置
mini-db-router:
  jdbc:
    datasource:
      dbCount: 2
      tbCount: 4
      default: db00
      routerKey: uId
      list: db01,db02
      db00:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://xx.xx.xxx.xx.xxxx/xxxx?useUnicode=true
        username: xxxx
        password: xxx
      db01:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://xx.xx.xxx.xx.xxxx/xxxx_01?useUnicode=true
        username: xxxx_01
        password: xxx
      db02:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://xx.xx.xxx.xx.xxxx/xxxx_02?useUnicode=true
        username: xxxx_02
        password: xxx
mybatis:
  mapper-locations: classpath:/com/xbhog/mapper/*.xml
  config-location:  classpath:/config/mybatis-config.xml